# Generated by Django 2.0.4 on 2018-04-25 11:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutpage_about_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
