# Generated by Django 2.0.4 on 2018-04-25 18:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_event_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='event_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}'),
            preserve_default=False,
        ),
    ]
