# Generated by Django 2.0.4 on 2018-04-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180425_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
