# Generated by Django 2.0.4 on 2018-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180426_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123.5, max_digits=6),
            preserve_default=False,
        ),
    ]
