# Generated by Django 2.0.4 on 2018-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shopitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='raw_description',
            field=models.TextField(blank=True),
        ),
    ]
